# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_management', '0011_auto_20181010_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyccoMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('green_point', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_greenpoint', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyccoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('phone_no', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Zip')),
            ],
        ),
    ]
