# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycler_management', '0005_auto_20181012_1337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_management', '0020_loaddashboard_remarks'),
        ('sycco_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyccoHRtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelsycco_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.HotelMaster')),
                ('recyclersyco_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycler_management.RecyclerMaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
