# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_management', '0006_auto_20181003_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclerMaster',
            fields=[
                ('recycler_id', models.AutoField(primary_key=True, serialize=False)),
                ('recycler_name', models.CharField(max_length=150)),
                ('recycler_address1', models.CharField(max_length=150)),
                ('recycler_address2', models.CharField(max_length=150)),
                ('recycler_phone_no', models.IntegerField()),
                ('recycler_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.City')),
                ('recycler_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Country')),
                ('recycler_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.State')),
                ('recycler_zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Zip')),
            ],
        ),
    ]
