# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycler_management', '0002_recyclermaster_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclermaster',
            name='user',
        ),
    ]
