# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HotelMaster',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_address1', models.CharField(max_length=150)),
                ('hotel_address2', models.CharField(max_length=150)),
                ('hotel_phone_no', models.IntegerField()),
                ('hotel_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Brand')),
                ('hotel_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.City')),
                ('hotel_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('zip_id', models.AutoField(primary_key=True, serialize=False)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hotelmaster',
            name='hotel_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.State'),
        ),
        migrations.AddField(
            model_name='hotelmaster',
            name='hotel_zip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Zip'),
        ),
    ]
