# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 11:47
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_management', '0002_auto_20181003_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadDashboard',
            fields=[
                ('load_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('contact_details', models.IntegerField()),
                ('status', models.CharField(default='Processing', max_length=150)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('no_of_bags', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('actual_no_of_bags', models.IntegerField()),
                ('actual_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('green_point_hotel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('green_point_recycler', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Category')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.HotelMaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_management.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
