# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0003_loaddashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddashboard',
            name='actual_no_of_bags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
