# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0010_syccomaster_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syccomaster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='syccoprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='syccoprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='syccoprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='syccoprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='syccoprofile',
            name='zip',
        ),
        migrations.DeleteModel(
            name='SyccoMaster',
        ),
        migrations.DeleteModel(
            name='SyccoProfile',
        ),
    ]
