# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0014_auto_20181017_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddashboard',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
