# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0016_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='remark_load',
        ),
        migrations.AddField(
            model_name='loaddashboard',
            name='remarks',
            field=models.TextField(blank=True, max_length=524, null=True),
        ),
        migrations.AddField(
            model_name='remark',
            name='remark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel_management.LoadDashboard'),
        ),
    ]
