# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0017_auto_20181025_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='remark',
            new_name='load_remark',
        ),
        migrations.RemoveField(
            model_name='loaddashboard',
            name='remarks',
        ),
    ]
