# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0019_auto_20181025_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddashboard',
            name='remarks',
            field=models.TextField(blank=True, max_length=524, null=True),
        ),
    ]
