# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0020_loaddashboard_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
