# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0022_auto_20181113_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddashboard',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
