# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-23 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0023_auto_20181123_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddashboard',
            name='actual_no_of_bags',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loaddashboard',
            name='actual_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loaddashboard',
            name='contact_details',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loaddashboard',
            name='green_point_hotel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loaddashboard',
            name='green_point_recycler',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loaddashboard',
            name='no_of_bags',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
