# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0024_auto_20181123_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddashboard',
            name='hotel_conf',
            field=models.CharField(default='NO', max_length=150),
        ),
    ]
