# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-26 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0025_loaddashboard_hotel_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaddashboard',
            name='hotel_conf',
        ),
    ]
