# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0026_remove_loaddashboard_hotel_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddashboard',
            name='hotel_conf',
            field=models.CharField(default='NO', max_length=150),
        ),
    ]
